"""Added field to service model

Revision ID: 3883a20934a1
Revises: 2ce91103e5cd
Create Date: 2026-04-05 14:46:11.385754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3883a20934a1'
down_revision: Union[str, None] = '2ce91103e5cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('is_working', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'is_working')
    # ### end Alembic commands ###
